<?php

namespace ReservationBundle\Repository;

/**
 * ClassroomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassroomsRepository extends \Doctrine\ORM\EntityRepository
{
}
