<?php

namespace ReservationBundle\Repository;

/**
 * LessonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonsRepository extends \Doctrine\ORM\EntityRepository
{
}
